var once_true = [1,5,10,14,18,22];
var database = {
    1: {
      name: "落石（效果）",
      content: "到自己的反擊階段時，點數暫時上升２點。",
      attributes: "dust",
      cardlevel: 1,
      handslect: [3],  // 2、3攻擊 4、5效果 6、7防禦
      fieldslect: [],
    },
    2: {
      name: "土法師（常規）",
      content: "攻擊時點數暫時上升３，防禦時點數暫時下降１。",
      attributes: "dust",
      cardlevel: 2,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    3: {
      name: "城牆（防禦）",
      content: "防禦時點數暫時上升４，攻擊時點數暫時下降２。",
      attributes: "dust",
      cardlevel: 3,
      handslect: [4],
      fieldslect: [4],
    },
    4: {
      name: "石巨人（常規）",
      content: "防禦時點數暫時上升５，攻擊時點數暫時下降１。",
      attributes: "dust",
      cardlevel: 4,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    5: {
      name: "地震（效果）",
      content: "對敵全體造成攻擊。",
      attributes: "dust",
      cardlevel: 5,
      handslect: [3],
      fieldslect: [],
    },
    6: {
      name: "沙塵暴（場地）",
      content: "卡牌放置於場上時，我方的水屬性卡牌點數上升２點。",
      attributes: "dust",
      cardlevel: 6,
      handslect: [4],
      fieldslect: [4],
    },
    7: {
      name: "泥沼（場地）",
      content: "卡牌放置於場上時，對方攻擊狀態卡牌點數下降１點。",
      attributes: "dust",
      cardlevel: 7,
      handslect: [4],
      fieldslect: [4],
    },
    8: {
      name: "梅杜莎（常規－效果）",
      content: "攻擊時點數可以暫時降低３點使用石化（無法行動一回合）",
      attributes: "dust",
      cardlevel: 8,
      handslect: [2,4],
      fieldslect: [2,3,4],
    },
    9: {
      name: "堡壘（防禦）",
      content: "防禦時點數暫時上升５，攻擊時點數暫時下降２",
      attributes: "dust",
      cardlevel: 9,
      handslect: [4],
      fieldslect: [4],
    },
    10: {
      name: "天崩地裂（效果）",
      content: "對敵全體卡牌隨機造成五點傷害，並轉為防守狀態。",
      attributes: "dust",
      cardlevel: 10,
      handslect: [3],
      fieldslect: [],
    },
    11: {
      name: "騎士（常規）",
      content: "",
      attributes: "dust",
      cardlevel: 11,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    12: {
      name: "皇后（常規）",
      content: "",
      attributes: "dust",
      cardlevel: 12,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    13: {
      name: "國王（常規）",
      content: "",
      attributes: "dust",
      cardlevel: 13,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    14: {
      name: "水彈（效果）",
      content: "到自己的反擊階段時，點數暫時上升２點。",
      attributes: "water",
      cardlevel: 1,
      handslect: [3],
      fieldslect: [],
    },
    15: {
      name: "冰法師（常規）",
      content: "攻擊時點數暫時上升３，防禦時點數暫時下降１。",
      attributes: "water",
      cardlevel: 2,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    16: {
      name: "冰牆（防禦）",
      content: "防禦時點數暫時上升４，攻擊時點數暫時下降２",
      attributes: "water",
      cardlevel: 3,
      handslect: [4],
      fieldslect: [4],
    },
    17: {
      name: "水母（常規）",
      content: "被攻擊後，對方的卡牌點數永久下降２點",
      attributes: "water",
      cardlevel: 4,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    18: {
      name: "冰封（效果）",
      content: "敵方單體卡牌冰封狀態三回合。",
      attributes: "water",
      cardlevel: 5,
      handslect: [3],
      fieldslect: [],
    },
    19: {
      name: "雪地（場地）",
      content: "卡牌放置於場上時，我方的水屬性卡牌點數上升２點。",
      attributes: "water",
      cardlevel: 6,
      handslect: [4],
      fieldslect: [4],
    },
    20: {
      name: "暴雨（場地）",
      content: "卡牌放置於場上時，對方的火屬性卡牌點數下降２點。",
      attributes: "water",
      cardlevel: 7,
      handslect: [4],
      fieldslect: [4],
    },
    21: {
      name: "冰龍（常規－效果）",
      content: "攻擊時可以選擇範圍攻擊，點數暫時下降３，對敵全體卡牌造成攻擊。",
      attributes: "water",
      cardlevel: 8,
      handslect: [2,4],
      fieldslect: [2,3,4],
    },
    22: {
      name: "暴風雪（效果）",
      content: "對敵全體卡牌隨機造成五～十點傷害。",
      attributes: "water",
      cardlevel: 9,
      handslect: [3],
      fieldslect: [],
    },
    23: {
      name: "絕對零度（效果）",
      content: "將對方場上的一張卡牌永久冰封（無法行動、攻擊）。（一次性）",
      attributes: "water",
      cardlevel: 10,
      handslect: [3],
      fieldslect: [0],
    },
    24: {
      name: "騎士（常規）",
      content: "",
      attributes: "water",
      cardlevel: 11,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    25: {
      name: "皇后（常規）",
      content: "",
      attributes: "water",
      cardlevel: 12,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    26: {
      name: "國王（常規）",
      content: "",
      attributes: "water",
      cardlevel: 13,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    27: {
      name: "火球（效果）",
      content: "到自己的反擊階段時，點數暫時上升２點。",
      attributes: "fire",
      cardlevel: 1,
      handslect: [3],
      fieldslect: [],
    },
    28: {
      name: "火法師（常規）",
      content: "攻擊時點數暫時上升３，防禦時點數暫時下降１。",
      attributes: "fire",
      cardlevel: 2,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    29: {
      name: "炎牆（防禦）",
      content: "防禦時點數暫時上升４，攻擊時點數暫時下降２",
      attributes: "fire",
      cardlevel: 3,
      handslect: [4],
      fieldslect: [4],
    },
    30: {
      name: "自爆兵（常規－效果）",
      content: "攻擊時可以選擇自爆，點數暫時上升３",
      attributes: "fire",
      cardlevel: 4,
      handslect: [2,4],
      fieldslect: [2,3,4],
    },
    31: {
      name: "惡魔（常規－效果）",
      content: "每次攻擊前必須捨棄一張手牌，同時點數永久上升３點。",
      attributes: "fire",
      cardlevel: 5,
      handslect: [2,4],
      fieldslect: [2,3,4],
    },
    32: {
      name: "煉獄（場地）",
      content: "卡牌放置於場上時，我方的火屬性卡牌點數上升２點。",
      attributes: "fire",
      cardlevel: 6,
      handslect: [4],
      fieldslect: [4],
    },
    33: {
      name: "陽光（場地）",
      content: "卡牌放置於場上時，對方的水屬性卡牌點數下降２點。",
      attributes: "fire",
      cardlevel: 7,
      handslect: [4],
      fieldslect: [4],
    },
    34: {
      name: "火龍（常規－效果）",
      content: "攻擊時可以選擇範圍攻擊，點數暫時下降３",
      attributes: "fire",
      cardlevel: 8,
      handslect: [2,4],
      fieldslect: [2,3,4],
    },
    35: {
      name: "流星雨（效果）",
      content: "對敵全體卡牌隨機造成五～十點傷害。",
      attributes: "fire",
      cardlevel: 9,
      handslect: [3],
      fieldslect: [],
    },
    36: {
      name: "核彈（效果）",
      content: "不分敵我，所有卡牌受到點數＋５的傷害。",
      attributes: "fire",
      cardlevel: 10,
      handslect: [3],
      fieldslect: [],
    },
    37: {
      name: "騎士（常規）",
      content: "",
      attributes: "fire",
      cardlevel: 11,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    38: {
      name: "皇后（常規）",
      content: "",
      attributes: "fire",
      cardlevel: 12,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    39: {
      name: "國王（常規）",
      content: "",
      attributes: "fire",
      cardlevel: 13,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    40: {
      name: "風刃（效果）",
      content: "到自己的反擊階段時，點數暫時上升２點。",
      attributes: "wind",
      cardlevel: 1,
      handslect: [3],
      fieldslect: [],
    },
    41: {
      name: "風法師（常規）",
      content: "攻擊時點數暫時上升３，防禦時點數暫時下降１。",
      attributes: "wind",
      cardlevel: 2,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    42: {
      name: "風障（防禦）",
      content: "防禦時點數暫時上升４，攻擊時點數暫時下降２。",
      attributes: "wind",
      cardlevel: 3,
      handslect: [4],
      fieldslect: [4],
    },
    43: {
      name: "旋風（效果）",
      content: "對敵全體卡牌造成攻擊。",
      attributes: "wind",
      cardlevel: 4,
      handslect: [3],
      fieldslect: [],
    },
    44: {
      name: "風狼（常規）",
      content: "攻擊時點數暫時上升４，被攻擊時點數下降４",
      attributes: "wind",
      cardlevel: 5,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    45: {
      name: "勇氣之風（效果）",
      content: "選擇場上一張卡，卡片變為攻擊狀態。",
      attributes: "wind",
      cardlevel: 6,
      handslect: [3],
      fieldslect: [],
    },
    46: {
      name: "神速（效果）",
      content: "選擇我方場上的一張卡，本回合可以行動兩次。",
      attributes: "wind",
      cardlevel: 7,
      handslect: [3],
      fieldslect: [],
    },
    47: {
      name: "精靈（常規）",
      content: "攻擊時，轉化為能克制該卡的屬性。",
      attributes: "wind",
      cardlevel: 8,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    48: {
      name: "颱風（效果）",
      content: "對敵全體卡牌隨機造成五～十點傷害。",
      attributes: "wind",
      cardlevel: 9,
      handslect: [3],
      fieldslect: [],
    },
    49: {
      name: "風神之舞（效果）",
      content: "所有風屬性卡牌點數暫時上升五點。",
      attributes: "wind",
      cardlevel: 10,
      handslect: [3],
      fieldslect: [],
    },
    50: {
      name: "騎士（常規）",
      content: "",
      attributes: "wind",
      cardlevel: 11,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    51: {
      name: "皇后（常規）",
      content: "",
      attributes: "wind",
      cardlevel: 12,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    52: {
      name: "國王（常規）",
      content: "",
      attributes: "wind",
      cardlevel: 13,
      handslect: [2,4],
      fieldslect: [2,4],
    },
    53: {
      name: "黑洞（效果）",
      content: "破壞場上所有卡牌。",
      attributes: "dark",
      cardlevel: '??',
      handslect: [3],
      fieldslect: [],
    },
    54: {
      name: "神的祝福（效果）",
      content: "手排補充至十張。",
      attributes: "light",
      cardlevel: '??',
      handslect: [3],
      fieldslect: [],
    },
};
  